// Real HouseClass owner objects; map session does not start AI/economy managers.
// Original constructor: 0x004F54A0.
#include "yrpp/HouseClass.h"
#include "yrpp/ScenarioClass.h"
#include "yrpp/WaypointPathClass.h"
#include "yrpp/Notifications.h"
#include "scenario_runtime.hpp"
#include <cstdio>
HouseClass* YRPP_FASTCALL HouseClass::FindByCountryIndex(int country) {
 for(auto* house:Array)if(house->Type->ArrayIndex==country)return house;
 return nullptr;
}
HouseClass* YRPP_FASTCALL HouseClass::FindByIndex(int playerAt) {
 if(!Index_IsMP(playerAt))return nullptr;
 return Array.GetItemOrDefault(ScenarioClass::Instance->HouseIndices[playerAt-PlayerAtA]);
}
bool HouseClass::IsControlledByHuman() const {
 const auto& runtime=game::scenario_runtime();
 return IsHumanPlayer || (runtime.session_mode(runtime.context)==int(GameMode::Campaign) && IsInPlayerControl);
}
bool HouseClass::IsControlledByCurrentPlayer() const {
 const auto& runtime=game::scenario_runtime();
 return runtime.session_mode(runtime.context)==int(GameMode::Campaign) ? IsHumanPlayer||IsInPlayerControl : IsCurrentPlayer();
}
namespace {DynamicVectorClass<HouseClass*> houses;HouseClass*player=nullptr;HouseClass*observer=nullptr;}
DynamicVectorClass<HouseClass*>& HouseClass::Array=houses;
HouseClass*& HouseClass::CurrentPlayer=player;
HouseClass*& HouseClass::Observer=observer;
HouseClass::HouseClass(HouseTypeClass*pType) noexcept
 : AbstractClass(),
 ArrayIndex{},
 Type{},
 RelatedTags{},
 ConYards{},
 Buildings{},
 UnitRepairStations{},
 Grinders{},
 Absorbers{},
 Bunkers{},
 Occupiables{},
 CloningVats{},
 SecretLabs{},
 PsychicDetectionBuildings{},
 FactoryPlants{},
 CountResourceGatherers{},
 CountResourceDestinations{},
 CountWarfactories{},
 InfantrySelfHeal{},
 UnitsSelfHeal{},
 StartingUnits{},
 AIDifficulty{},
 FirepowerMultiplier{},
 GroundspeedMultiplier{},
 AirspeedMultiplier{},
 ArmorMultiplier{},
 ROFMultiplier{},
 CostMultiplier{},
 BuildTimeMultiplier{},
 RepairDelay{},
 BuildDelay{},
 IQLevel{},
 TechLevel{},
 AltAllies{},
 StartingCredits{},
 StartingEdge{},
 AIState_1E4{},
 SideIndex{},
 IsHumanPlayer{},
 IsInPlayerControl{},
 Production{},
 AutocreateAllowed{},
 NodeLogic_1F0{},
 ShipYardConst_1F1{},
 AITriggersActive{},
 AutoBaseBuilding{},
 DiscoveredByPlayer{},
 Defeated{},
 IsGameOver{},
 IsWinner{},
 IsLoser{},
 CiviliansEvacuated{},
 FirestormActive{},
 HasThreatNode{},
 RecheckTechTree{},
 IPAddress{},
 TournamentTeamID{},
 LostConnection{},
 SelectedPathIndex{},
 PlanningPaths{},
 Visionary{},
 MapIsClear{},
 IsTiberiumShort{},
 HasBeenSpied{},
 HasBeenThieved{},
 Repairing{},
 IsBuiltSomething{},
 IsResigner{},
 IsGiverUpper{},
 AllToHunt{},
 IsParanoid{},
 IsToLook{},
 IQLevel2{},
 AIMode{},
 Supers{},
 LastBuiltBuildingType{},
 LastBuiltInfantryType{},
 LastBuiltAircraftType{},
 LastBuiltVehicleType{},
 AllowWinBlocks{},
 RepairTimer{},
 AlertTimer{},
 BorrowedTime{},
 PowerBlackoutTimer{},
 RadarBlackoutTimer{},
 Side2TechInfiltrated{},
 Side1TechInfiltrated{},
 Side0TechInfiltrated{},
 BarracksInfiltrated{},
 WarFactoryInfiltrated{},
 InfantryAltOwner{},
 UnitAltOwner{},
 AircraftAltOwner{},
 BuildingAltOwner{},
 AirportDocks{},
 PoweredUnitCenters{},
 CreditsSpent{},
 HarvestedCredits{},
 StolenBuildingsCredits{},
 OwnedUnits{},
 OwnedNavy{},
 OwnedBuildings{},
 OwnedInfantry{},
 OwnedAircraft{},
 OwnedTiberium{},
 Balance{},
 TotalStorage{},
 OwnedWeed{},
 unknown_324{},
 BuiltAircraftTypes{},
 BuiltInfantryTypes{},
 BuiltUnitTypes{},
 BuiltBuildingTypes{},
 KilledAircraftTypes{},
 KilledInfantryTypes{},
 KilledUnitTypes{},
 KilledBuildingTypes{},
 CapturedBuildings{},
 CollectedCrates{},
 NumAirpads{},
 NumBarracks{},
 NumWarFactories{},
 NumConYards{},
 NumShipyards{},
 NumOrePurifiers{},
 CostInfantryMult{},
 CostUnitsMult{},
 CostAircraftMult{},
 CostBuildingsMult{},
 CostDefensesMult{},
 PowerOutput{},
 PowerDrain{},
 Primary_ForAircraft{},
 Primary_ForInfantry{},
 Primary_ForVehicles{},
 Primary_ForShips{},
 Primary_ForBuildings{},
 Primary_Unused1{},
 Primary_Unused2{},
 Primary_Unused3{},
 Primary_ForDefenses{},
 AircraftType_53D0{},
 InfantryType_53D1{},
 VehicleType_53D2{},
 ShipType_53D3{},
 BuildingType_53D4{},
 unknown_53D5{},
 unknown_53D6{},
 unknown_53D7{},
 DefenseType_53D8{},
 unknown_53D9{},
 unknown_53DA{},
 unknown_53DB{},
 OurFlagCarrier{},
 OurFlagCoords{},
 KilledUnitsOfHouses{},
 TotalKilledUnits{},
 KilledBuildingsOfHouses{},
 TotalKilledBuildings{},
 WhoLastHurtMe{},
 BaseSpawnCell{},
 BaseCenter{},
 Radius{},
 ZoneInfos{},
 LATime{},
 LAEnemy{},
 ToCapture{},
 RadarVisibleTo{},
 PointTotal{},
 PreferredTargetType{},
 PreferredTargetCell{},
 PreferredDefensiveCell{},
 PreferredDefensiveCell2{},
 PreferredDefensiveCellStartTime{},
 OwnedBuildingTypes{},
 OwnedUnitTypes{},
 OwnedInfantryTypes{},
 OwnedAircraftTypes{},
 ActiveBuildingTypes{},
 ActiveUnitTypes{},
 ActiveInfantryTypes{},
 ActiveAircraftTypes{},
 FactoryProducedBuildingTypes{},
 FactoryProducedUnitTypes{},
 FactoryProducedInfantryTypes{},
 FactoryProducedAircraftTypes{},
 AttackTimer{},
 InitialAttackDelay{},
 EnemyHouseIndex{},
 AngerNodes{},
 ScoutNodes{},
 AITimer{},
 Unknown_Timer_5640{},
 ProducingBuildingTypeIndex{},
 ProducingUnitTypeIndex{},
 ProducingInfantryTypeIndex{},
 ProducingAircraftTypeIndex{},
 RatioAITriggerTeam{},
 RatioTeamAircraft{},
 RatioTeamInfantry{},
 RatioTeamBuildings{},
 BaseDefenseTeamCount{},
 DropshipData{},
 CurrentDropshipIndex{},
 HasCloakingRanges{},
 Color{},
 LaserColor{},
 Base{},
 RecheckPower{},
 RecheckRadar{},
 SpySatActive{},
 IsBeingDrained{},
 Edge{},
 EMPTarget{},
 NukeTarget{},
 Allies{},
 DamageDelayTimer{},
 TeamDelayTimer{},
 TriggerDelayTimer{},
 SpeakAttackDelayTimer{},
 SpeakPowerDelayTimer{},
 SpeakMoneyDelayTimer{},
 SpeakMaxedDelayTimer{},
 AIGeneral{},
 ThreatPosedEstimates{},
 PlainName{},
 UINameString{},
 UIName{},
 ColorSchemeIndex{},
 StartingPoint{},
 StartingAllies{},
 unknown_16060{},
 WaypointPath{},
 unknown_1607C{},
 unknown_16080{},
 unknown_16084{},
 unused_16088{},
 unused_16090{},
 padding_16098{},
 PredictionEnemyArmor{},
 PredictionEnemyAir{},
 PredictionEnemyInfantry{},
 TotalOwnedInfantryCost{},
 TotalOwnedVehicleCost{},
 TotalOwnedAircraftCost{},
 PowerSurplus{} {
 Type=pType;ArrayIndex=Array.Count;SideIndex=pType?pType->SideIndex:-1;
 FirepowerMultiplier=GroundspeedMultiplier=AirspeedMultiplier=ArmorMultiplier=ROFMultiplier=CostMultiplier=BuildTimeMultiplier=1.0;
 CostInfantryMult=CostUnitsMult=CostAircraftMult=CostBuildingsMult=CostDefensesMult=1.0f;
 Color=pType?ColorStruct{128,128,128}:ColorStruct{};Base.Owner=this;
 if(pType)std::snprintf(PlainName,sizeof(PlainName),"%s",pType->ID);Create_ID();Array.AddItem(this);
 PointerExpiredNotification::NotifyInvalidWaypoint.Add(this);
}
HouseClass::~HouseClass(){if(CurrentPlayer==this)CurrentPlayer=nullptr;if(Observer==this)Observer=nullptr;Array.Remove(this);
 // Original 0x004F7140 retires each owned path before the remaining vectors.
 for(auto*& path:PlanningPaths){GameDelete(path);path=nullptr;}
 PointerExpiredNotification::NotifyInvalidWaypoint.Remove(this);
 RelatedTags.~DynamicVectorClass();
 ConYards.~DynamicVectorClass();
 Buildings.~DynamicVectorClass();
 UnitRepairStations.~DynamicVectorClass();
 Grinders.~DynamicVectorClass();
 Absorbers.~DynamicVectorClass();
 Bunkers.~DynamicVectorClass();
 Occupiables.~DynamicVectorClass();
 CloningVats.~DynamicVectorClass();
 SecretLabs.~DynamicVectorClass();
 PsychicDetectionBuildings.~DynamicVectorClass();
 FactoryPlants.~DynamicVectorClass();
 StartingUnits.~DynamicVectorClass();
 Supers.~DynamicVectorClass();
 OwnedBuildingTypes.~CounterClass();
 OwnedUnitTypes.~CounterClass();
 OwnedInfantryTypes.~CounterClass();
 OwnedAircraftTypes.~CounterClass();
 ActiveBuildingTypes.~CounterClass();
 ActiveUnitTypes.~CounterClass();
 ActiveInfantryTypes.~CounterClass();
 ActiveAircraftTypes.~CounterClass();
 FactoryProducedBuildingTypes.~CounterClass();
 FactoryProducedUnitTypes.~CounterClass();
 FactoryProducedInfantryTypes.~CounterClass();
 FactoryProducedAircraftTypes.~CounterClass();
 AngerNodes.~DynamicVectorClass();
 ScoutNodes.~DynamicVectorClass();
 for (auto& item : DropshipData) item.~DropshipStruct();
 WaypointPath.~DynamicVectorClass();
}
