/*
 * Adapts fields/section-reader structure from EA REDALERT/RULES.CPP, fixed
 * f1f0d42bc2dcd06d5d1df943c6150ab34bf307ae. Copyright 2020 Electronic Arts
 * Inc. GPL-3.0-or-later with terms in third_party/ea/LICENSE.TXT.
 * YR's field types, query order, conversions and type references are
 * calibrated against the fixed EXE entry 6691E0.
 */
#include "yrpp/RulesClass.h"
#include "yrpp/AnimTypeClass.h"
#include "RulesClassReaders.hpp"

bool RulesClass::Read_AudioVisual(CCINIClass* ini) {
    const char* section = "AudioVisual";
    if (!ini || !ini->GetSection(section)) return false;
    DetailMinFrameRateNormal = ini->ReadInteger(section, "DetailMinFrameRateNormal", DetailMinFrameRateNormal);
    DetailMinFrameRateMovie = ini->ReadInteger(section, "DetailMinFrameRateMovie", DetailMinFrameRateMovie);
    DetailBufferZoneWidth = ini->ReadInteger(section, "DetailBufferZoneWidth", DetailBufferZoneWidth);
    PoseDir = ini->ReadInteger(section, "PoseDir", PoseDir);
    DeployDir = std::bit_cast<std::int32_t>(static_cast<std::uint32_t>(ini->ReadInteger(section, "DeployDir", DeployDir >> 5)) << 5);
    read_rule_type(*ini, section, "DropPodPuff", AbstractType::AnimType, DropPodPuff);
    WaypointAnimationSpeed = ini->ReadInteger(section, "WaypointAnimationSpeed", WaypointAnimationSpeed);
    read_rule_type(*ini, section, "VeinAttack", AbstractType::AnimType, VeinAttack);
    read_rule_sound(*ini, section, "DigSound", DigSound);
    read_rule_sound(*ini, section, "GUIMainButtonSound", GUIMainButtonSound);
    read_rule_sound(*ini, section, "GUIBuildSound", GUIBuildSound);
    read_rule_sound(*ini, section, "GUITabSound", GUITabSound);
    read_rule_sound(*ini, section, "GUIOpenSound", GUIOpenSound);
    read_rule_sound(*ini, section, "GUICloseSound", GUICloseSound);
    read_rule_sound(*ini, section, "GUIMoveOutSound", GUIMoveOutSound);
    read_rule_sound(*ini, section, "GUIMoveInSound", GUIMoveInSound);
    read_rule_sound(*ini, section, "GUIComboOpenSound", GUIComboOpenSound);
    read_rule_sound(*ini, section, "GUIComboCloseSound", GUIComboCloseSound);
    read_rule_sound(*ini, section, "GUICheckboxSound", GUICheckboxSound);
    read_rule_sound(*ini, section, "ScoreAnimSound", ScoreAnimSound);
    read_rule_sound(*ini, section, "CheerSound", CheerSound);
    read_rule_sound(*ini, section, "DefaultChronoSound", DefaultChronoSound);
    read_rule_sound(*ini, section, "StartPlanningModeSound", StartPlanningModeSound);
    read_rule_sound(*ini, section, "EndPlanningModeSound", EndPlanningModeSound);
    read_rule_sound(*ini, section, "CrateMoneySound", CrateMoneySound);
    read_rule_sound(*ini, section, "CrateRevealSound", CrateRevealSound);
    read_rule_sound(*ini, section, "CrateFireSound", CrateFireSound);
    read_rule_sound(*ini, section, "CrateArmourSound", CrateArmourSound);
    read_rule_sound(*ini, section, "CrateSpeedSound", CrateSpeedSound);
    read_rule_sound(*ini, section, "CrateUnitSound", CrateUnitSound);
    read_rule_sound(*ini, section, "CratePromoteSound", CratePromoteSound);
    read_rule_sound(*ini, section, "ImpactWaterSound", ImpactWaterSound);
    read_rule_sound(*ini, section, "ImpactLandSound", ImpactLandSound);
    read_rule_sound(*ini, section, "SinkingSound", SinkingSound);
    read_rule_sound(*ini, section, "ChronoInSound", ChronoInSound);
    read_rule_sound(*ini, section, "ChronoOutSound", ChronoOutSound);
    read_rule_sound(*ini, section, "BombTickingSound", BombTickingSound);
    read_rule_sound(*ini, section, "BombAttachSound", BombAttachSound);
    read_rule_sound(*ini, section, "YuriMindControlSound", YuriMindControlSound);
    read_rule_sound(*ini, section, "AddPlanningModeCommandSound", AddPlanningModeCommandSound);
    read_rule_sound(*ini, section, "ExecutePlanSound", ExecutePlanSound);
    read_rule_sound(*ini, section, "PlaceBeaconSound", PlaceBeaconSound);
    read_rule_sound(*ini, section, "BuildingGarrisonedSound", BuildingGarrisonedSound);
    read_rule_sound(*ini, section, "BuildingAbandonedSound", BuildingAbandonedSound);
    read_rule_sound(*ini, section, "BuildingRepairedSound", BuildingRepairedSound);
    read_rule_sound(*ini, section, "BaseUnderAttackSound", BaseUnderAttackSound);
    read_rule_sound(*ini, section, "UpgradeVeteranSound", UpgradeVeteranSound);
    read_rule_sound(*ini, section, "UpgradeEliteSound", UpgradeEliteSound);
    read_rule_sound(*ini, section, "VoiceIFVRepair", VoiceIFVRepair);
    read_rule_sound(*ini, section, "SlavesFreeSound", SlavesFreeSound);
    read_rule_sound(*ini, section, "SlaveMinerDeploySound", SlaveMinerDeploySound);
    read_rule_sound(*ini, section, "SlaveMinerUndeploySound", SlaveMinerUndeploySound);
    read_rule_sound(*ini, section, "BunkerWallsUpSound", BunkerWallsUpSound);
    read_rule_sound(*ini, section, "BunkerWallsDownSound", BunkerWallsDownSound);
    read_rule_sound(*ini, section, "RepairBridgeSound", RepairBridgeSound);
    read_rule_sound(*ini, section, "PsychicDominatorActivateSound", PsychicDominatorActivateSound);
    read_rule_sound(*ini, section, "GeneticMutatorActivateSound", GeneticMutatorActivateSound);
    read_rule_sound(*ini, section, "PsychicRevealActivateSound", PsychicRevealActivateSound);
    read_rule_sound(*ini, section, "MasterMindOverloadDeathSound", MasterMindOverloadDeathSound);
    read_rule_sound(*ini, section, "AirstrikeAbortSound", AirstrikeAbortSound);
    read_rule_sound(*ini, section, "AirstrikeAttackVoice", AirstrikeAttackVoice);
    read_rule_sound(*ini, section, "MindClearedSound", MindClearedSound);
    read_rule_sound(*ini, section, "EnterGrinderSound", EnterGrinderSound);
    read_rule_sound(*ini, section, "LeaveGrinderSound", LeaveGrinderSound);
    read_rule_sound(*ini, section, "EnterBioReactorSound", EnterBioReactorSound);
    read_rule_sound(*ini, section, "LeaveBioReactorSound", LeaveBioReactorSound);
    read_rule_sound(*ini, section, "ActivateSound", ActivateSound);
    read_rule_sound(*ini, section, "DeactivateSound", DeactivateSound);
    read_rule_sound(*ini, section, "SpyPlaneCamera", SpyPlaneCamera);
    read_rule_sound(*ini, section, "LetsDoTheTimeWarpOutAgain", LetsDoTheTimeWarpOutAgain);
    read_rule_sound(*ini, section, "LetsDoTheTimeWarpInAgain", LetsDoTheTimeWarpInAgain);
    read_rule_sound(*ini, section, "DiskLaserChargeUp", DiskLaserChargeUp);
    SpyPlaneCameraFrames = ini->ReadInteger(section, "SpyPlaneCameraFrames", SpyPlaneCameraFrames);
    read_rule_sound(*ini, section, "CreateUnitSound", CreateUnitSound);
    read_rule_sound(*ini, section, "CreateInfantrySound", CreateInfantrySound);
    read_rule_sound(*ini, section, "CreateAircraftSound", CreateAircraftSound);
    read_rule_sound(*ini, section, "IFVTransformSound", IFVTransformSound);
    read_rule_sound(*ini, section, "PsychicSensorDetectSound", PsychicSensorDetectSound);
    read_rule_sound(*ini, section, "SpySatActivationSound", SpySatActivationSound);
    read_rule_sound(*ini, section, "SpySatDeactivationSound", SpySatDeactivationSound);
    read_rule_type(*ini, section, "Dig", AbstractType::AnimType, Dig);
    read_rule_type(*ini, section, "AtmosphereEntry", AbstractType::AnimType, AtmosphereEntry);
    read_rule_sound(*ini, section, "GateUp", GateUp);
    read_rule_sound(*ini, section, "GateDown", GateDown);
    ShroudGrow = ini->ReadBool(section, "ShroudGrow", ShroudGrow);
    ScrollMultiplier = ini->ReadDouble(section, "ScrollMultiplier", ScrollMultiplier);
    ShakeScreen = ini->ReadInteger(section, "ShakeScreen", ShakeScreen);
    read_rule_sound(*ini, section, "CloakSound", CloakSound);
    read_rule_sound(*ini, section, "SellSound", SellSound);
    read_rule_sound(*ini, section, "GameClosed", GameClosed);
    read_rule_sound(*ini, section, "IncomingMessage", IncomingMessage);
    read_rule_sound(*ini, section, "MessageCharTyped", MessageCharTyped);
    read_rule_sound(*ini, section, "SystemError", SystemError);
    read_rule_sound(*ini, section, "OptionsChanged", OptionsChanged);
    read_rule_sound(*ini, section, "GameForming", GameForming);
    read_rule_sound(*ini, section, "PlayerLeft", PlayerLeft);
    read_rule_sound(*ini, section, "PlayerJoined", PlayerJoined);
    read_rule_sound(*ini, section, "Construction", Construction);
    read_rule_sound_list(*ini, section, "CreditTicks", CreditTicks);
    read_rule_sound(*ini, section, "BuildingDieSound", BuildingDieSound);
    read_rule_sound(*ini, section, "BuildingSlam", BuildingSlam);
    read_rule_sound(*ini, section, "RadarOn", RadarOn);
    read_rule_sound(*ini, section, "RadarOff", RadarOff);
    read_rule_sound(*ini, section, "MovieOn", MovieOn);
    read_rule_sound(*ini, section, "MovieOff", MovieOff);
    read_rule_sound(*ini, section, "ScoldSound", ScoldSound);
    read_rule_sound(*ini, section, "TeslaCharge", TeslaCharge);
    read_rule_sound(*ini, section, "TeslaZap", TeslaZap);
    read_rule_sound(*ini, section, "BuildingDamageSound", BuildingDamageSound);
    read_rule_sound(*ini, section, "ChuteSound", ChuteSound);
    read_rule_sound(*ini, section, "GenericClick", GenericClick);
    read_rule_sound(*ini, section, "GenericBeep", GenericBeep);
    read_rule_sound(*ini, section, "BuildingDrop", BuildingDrop);
    read_rule_sound(*ini, section, "StopSound", StopSound);
    read_rule_sound(*ini, section, "GuardSound", GuardSound);
    read_rule_sound(*ini, section, "ScatterSound", ScatterSound);
    read_rule_sound(*ini, section, "StormSound", StormSound);
    read_rule_sound_list(*ini, section, "LightningSounds", LightningSounds);
    read_rule_sound(*ini, section, "ShellButtonSlideSound", ShellButtonSlideSound);
    read_rule_type_list(*ini, section, "TreeFire", AbstractType::AnimType, TreeFire);
    read_rule_type_list(*ini, section, "OnFire", AbstractType::AnimType, OnFire);
    read_rule_type(*ini, section, "Smoke", AbstractType::AnimType, Smoke);
    read_rule_type(*ini, section, "Smoke", AbstractType::AnimType, Smoke_);
    EliteFlashTimer = ini->ReadInteger(section, "EliteFlashTimer", EliteFlashTimer);
    read_rule_type(*ini, section, "SmallFire", AbstractType::AnimType, SmallFire);
    read_rule_type(*ini, section, "LargeFire", AbstractType::AnimType, LargeFire);
    AllyReveal = ini->ReadBool(section, "AllyReveal", AllyReveal);
    ConditionGreen = 1.0;
    ConditionRed = ini->ReadDouble(section, "ConditionRed", ConditionRed);
    ConditionYellow = ini->ReadDouble(section, "ConditionYellow", ConditionYellow);
    DropZoneRadius = read_rule_distance(*ini, section, "DropZoneRadius", DropZoneRadius);
    EnemyHealth = ini->ReadBool(section, "EnemyHealth", EnemyHealth);
    Gravity = ini->ReadInteger(section, "Gravity", Gravity);
    IdleActionFrequency = ini->ReadDouble(section, "IdleActionFrequency", IdleActionFrequency);
    MessageDelay = ini->ReadDouble(section, "MessageDelay", MessageDelay);
    MovieTime = ini->ReadDouble(section, "MovieTime", MovieTime);
    NamedCivilians = ini->ReadBool(section, "NamedCivilians", NamedCivilians);
    SavourDelay = ini->ReadDouble(section, "SavourDelay", SavourDelay);
    ShroudRate = ini->ReadDouble(section, "ShroudRate", ShroudRate);
    FogRate = ini->ReadDouble(section, "FogRate", FogRate);
    VeinGrowthRate = ini->ReadDouble(section, "VeinGrowthRate", VeinGrowthRate);
    IceGrowthRate = ini->ReadDouble(section, "IceGrowthRate", IceGrowthRate);
    IceSolidifyFrameTime = ini->ReadInteger(section, "IceSolidifyFrameTime", IceSolidifyFrameTime);
    IceCrackSounds.Clear();
    read_rule_sound_list(*ini, section, "IceCrackSounds", IceCrackSounds);
    AmbientChangeRate = ini->ReadDouble(section, "AmbientChangeRate", AmbientChangeRate);
    AmbientChangeStep = ini->ReadDouble(section, "AmbientChangeStep", AmbientChangeStep);
    SpeakDelay = ini->ReadDouble(section, "SpeakDelay", SpeakDelay);
    TimerWarning = ini->ReadDouble(section, "TimerWarning", TimerWarning);
    ExtraUnitLight = rule_scaled_integer(ini->ReadDouble(section, "ExtraUnitLight", ExtraUnitLight / 1000), 1000);
    ExtraInfantryLight = rule_scaled_integer(ini->ReadDouble(section, "ExtraInfantryLight", ExtraInfantryLight / 1000), 1000);
    ExtraAircraftLight = rule_scaled_integer(ini->ReadDouble(section, "ExtraAircraftLight", ExtraAircraftLight / 1000), 1000);
    ini->Read3Bytes(reinterpret_cast<byte*>(&LocalRadarColor), section, "LocalRadarColor", reinterpret_cast<byte*>(&LocalRadarColor));
    ini->Read3Bytes(reinterpret_cast<byte*>(&LineTrailColorOverride), section, "LineTrailColorOverride", reinterpret_cast<byte*>(&LineTrailColorOverride));
    ini->Read3Bytes(reinterpret_cast<byte*>(&ChronoBeamColor), section, "ChronoBeamColor", reinterpret_cast<byte*>(&ChronoBeamColor));
    ini->Read3Bytes(reinterpret_cast<byte*>(&MagnaBeamColor), section, "MagnaBeamColor", reinterpret_cast<byte*>(&MagnaBeamColor));
    OreTwinkleChance = ini->ReadInteger(section, "OreTwinkleChance", OreTwinkleChance);
    LaserTargetColor = ini->ReadInteger(section, "LaserTargetColor", LaserTargetColor);
    IronCurtainColor = ini->ReadInteger(section, "IronCurtainColor", IronCurtainColor);
    BerserkColor = ini->ReadInteger(section, "BerserkColor", BerserkColor);
    ForceShieldColor = ini->ReadInteger(section, "ForceShieldColor", ForceShieldColor);
    DirectRockingCoefficient = static_cast<float>(ini->ReadDouble(section, "DirectRockingCoefficient", DirectRockingCoefficient));
    FallBackCoefficient = static_cast<float>(ini->ReadDouble(section, "FallBackCoefficient", FallBackCoefficient));
    return true;
}
