# macOS/Linux host -> Windows x86, Microsoft C++ ABI. Use a fresh Ninja build tree.
# Dependencies: clang-cl, lld-link, llvm-lib and an xwin --arch x86 splat.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    RA2_XWIN_ROOT RA2_LLVM_BIN RA2_LLD_BIN)

foreach(variable RA2_XWIN_ROOT RA2_LLVM_BIN RA2_LLD_BIN)
    if(NOT DEFINED ${variable} AND DEFINED ENV{${variable}})
        set(${variable} "$ENV{${variable}}" CACHE PATH "Cross-toolchain ${variable}")
    endif()
endforeach()
if(NOT RA2_XWIN_ROOT OR NOT IS_ABSOLUTE "${RA2_XWIN_ROOT}")
    message(FATAL_ERROR "Set RA2_XWIN_ROOT to the absolute xwin x86 splat directory.")
endif()
# Do not accidentally accept an x64 sysroot or xwin's alternative winsysroot layout.
foreach(required crt/include/vcruntime.h sdk/include/um/windows.h
        crt/lib/x86/msvcrt.lib sdk/lib/ucrt/x86/ucrt.lib sdk/lib/um/x86/kernel32.lib)
    if(NOT EXISTS "${RA2_XWIN_ROOT}/${required}")
        message(FATAL_ERROR "Incomplete x86 xwin sysroot: ${RA2_XWIN_ROOT}/${required}\nRun xwin --arch x86 splat --output <root> (default layout, keep symlinks).")
    endif()
endforeach()
find_program(RA2_CLANG_CL NAMES clang-cl HINTS "${RA2_LLVM_BIN}" REQUIRED)
find_program(RA2_LLD_LINK NAMES lld-link HINTS "${RA2_LLD_BIN}" "${RA2_LLVM_BIN}" REQUIRED)
find_program(RA2_LLVM_LIB NAMES llvm-lib HINTS "${RA2_LLVM_BIN}" REQUIRED)
find_program(RA2_LLVM_RC NAMES llvm-rc HINTS "${RA2_LLVM_BIN}")
set(CMAKE_C_COMPILER "${RA2_CLANG_CL}")
set(CMAKE_CXX_COMPILER "${RA2_CLANG_CL}")
set(CMAKE_C_COMPILER_TARGET i686-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET i686-pc-windows-msvc)
set(CMAKE_LINKER "${RA2_LLD_LINK}")
set(CMAKE_AR "${RA2_LLVM_LIB}")
if(RA2_LLVM_RC)
    set(CMAKE_RC_COMPILER "${RA2_LLVM_RC}")
endif()
set(_ra2_system_includes "")
foreach(directory crt/include sdk/include/ucrt sdk/include/shared sdk/include/um sdk/include/winrt)
    string(APPEND _ra2_system_includes " /imsvc\"${RA2_XWIN_ROOT}/${directory}\"")
endforeach()
set(CMAKE_C_FLAGS_INIT "${_ra2_system_includes}")
set(CMAKE_CXX_FLAGS_INIT "${_ra2_system_includes}")
set(_ra2_library_paths "")
foreach(directory crt/lib/x86 sdk/lib/ucrt/x86 sdk/lib/um/x86)
    string(APPEND _ra2_library_paths " /libpath:\"${RA2_XWIN_ROOT}/${directory}\"")
endforeach()
foreach(kind EXE SHARED MODULE)
    set(CMAKE_${kind}_LINKER_FLAGS_INIT "${_ra2_library_paths} /machine:x86")
endforeach()
# LLD embeds manifests itself. Avoid CMake's Windows-only mt.exe/vs_link helper.
set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/ClangMsvcLinkRules.cmake")
set(CMAKE_FIND_ROOT_PATH "${RA2_XWIN_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
