# Explicit standalone source set. Files elsewhere in core/ are not automatically portable.
include("${CMAKE_CURRENT_LIST_DIR}/SourceSets.cmake")
add_library(ra2_core STATIC
    core/src/projectile_diagnostics.cpp
    core/src/player_commands.cpp
    core/src/yrpp/CommandClass.cpp
    core/src/building_voxel.cpp
    core/src/building_selection.cpp
    core/src/building_drawing.cpp
    core/src/overlay_drawing.cpp
    core/src/sprite_drawing.cpp
    core/src/techno_drawing.cpp
    core/src/yrpp/TechnoClassDrawing.cpp
    core/src/yrpp/TechnoClassDrawingEffects.cpp
    core/src/yrpp/TechnoClassVoxelDrawing.cpp
    core/src/yrpp/FootClassDrawing.cpp
    core/src/yrpp/UnitClassDrawing.cpp
    core/src/yrpp/UnitClassVoxelDrawing.cpp
    core/src/yrpp/AircraftClassDrawing.cpp
    core/src/yrpp/AnimClassDrawing.cpp
    core/src/yrpp/TerrainClassDrawing.cpp
    core/src/yrpp/OverlayTypeClassOffset.cpp
    core/src/yrpp/CellClassOverlay.cpp
    core/src/yrpp/TiberiumClassOverlay.cpp
    core/src/yrpp/BuildingTypeClassRubble.cpp
    core/src/yrpp/BuildingClassDrawing.cpp
    core/src/yrpp/TransitionTimer.cpp
    core/src/map_objects.cpp
    core/src/map_world_drawing.cpp
    core/src/map_world.cpp
    core/src/map_configuration.cpp
    core/src/scenario_script_fields.cpp
    core/src/yrpp/AnimTypeClassINI.cpp
    core/src/yrpp/BuildingClassDamageFires.cpp
    core/src/yrpp/BuildingClassDamage.cpp
    core/src/yrpp/BuildingClassCommands.cpp
    core/src/yrpp/BuildingClassAnimations.cpp
    core/src/yrpp/BuildingTypeClassFoundations.cpp
    core/src/yrpp/BuildingTypeClassPlacement.cpp
    core/src/yrpp/DisplayClassPlacement.cpp
    core/src/yrpp/DisplayClassFoundation.cpp
    core/src/yrpp/DisplayClassModes.cpp
    core/src/yrpp/TextLabelClassDrawing.cpp
    core/src/yrpp/MessageListClassDrawing.cpp
    core/src/yrpp/OwnerDrawIME.cpp
    core/src/yrpp/OwnerDrawEditText.cpp
    core/src/yrpp/MessageListClass.cpp
    core/src/yrpp/TextLabelClass.cpp
    core/src/yrpp/GameMessages.cpp
    core/src/yrpp/BitFontString.cpp
    core/src/yrpp/BitTextPrint.cpp
    core/src/yrpp/OwnerDrawText.cpp
    core/src/yrpp/BitFontMeasurement.cpp
    core/src/yrpp/BeaconClassState.cpp
    core/src/yrpp/BeaconManagerClass.cpp
    core/src/yrpp/BeaconManagerClassArt.cpp
    core/src/yrpp/BeaconManagerClassDrawing.cpp
    core/src/yrpp/BeaconClassDrawing.cpp
    core/src/yrpp/BuildingClassUpgrade.cpp
    core/src/yrpp/GameSidebar.cpp
    core/src/yrpp/BuildingTypeClassINI.cpp
    core/src/yrpp/CellClassResources.cpp
    core/src/yrpp/CellClassBridge.cpp
    core/src/yrpp/TechnoTypeClassINI.cpp
    core/src/yrpp/TiberiumClassINI.cpp
    core/src/yrpp/ObjectClassLifecycle.cpp
    core/src/yrpp/ObjectClassUpdate.cpp
    core/src/yrpp/MissionClassUpdate.cpp
    core/src/yrpp/DisplayClassLayers.cpp
    core/src/yrpp/ObjectClassMark.cpp
    core/src/yrpp/TechnoClassMark.cpp
    core/src/yrpp/TechnoClassMovement.cpp
    core/src/yrpp/TechnoClassRocking.cpp
    core/src/yrpp/TechnoClassUpdate.cpp
    core/src/yrpp/TechnoClassCommands.cpp
    core/src/yrpp/TechnoClassClick.cpp
    core/src/yrpp/TechnoClassOwnership.cpp
    core/src/yrpp/TechnoClassRadio.cpp
    core/src/yrpp/ObjectClassRadio.cpp
    core/src/yrpp/FootClassRadio.cpp
    core/src/yrpp/HouseTypeClassINI.cpp
    core/src/yrpp/DriveLocomotionClass.cpp
    core/src/yrpp/DriveLocomotionClassMovement.cpp
    core/src/yrpp/DriveLocomotionClassTracks.cpp
    core/src/yrpp/DriveLocomotionClassDrawing.cpp
    core/src/yrpp/UnitClassMovement.cpp
    core/src/yrpp/UnitClassPassability.cpp
    core/src/yrpp/UnitTypeClassFactory.cpp
    core/src/yrpp/UnitTypeClassINI.cpp
    core/src/yrpp/UnitClassLifecycle.cpp
    core/src/yrpp/UnitClassRadio.cpp
    core/src/yrpp/UnitClassGunner.cpp
    core/src/yrpp/UnitClassUnload.cpp
    core/src/yrpp/UnitClassTargeting.cpp
    core/src/yrpp/UnitClassFiring.cpp
    core/src/yrpp/UnitClassDisguise.cpp
    core/src/yrpp/TechnoClassDisguise.cpp
    core/src/yrpp/UnitClassDamage.cpp
    core/src/yrpp/TechnoClassInput.cpp
    core/src/yrpp/FootClassInput.cpp
    core/src/yrpp/InfantryClassInput.cpp
    core/src/yrpp/EventClassConstruction.cpp
    core/src/yrpp/EventClassQueue.cpp
    core/src/yrpp/SuperWeaponTypeClassInput.cpp
    core/src/yrpp/EventClass.cpp
    core/src/yrpp/PlanningTokenClassCommands.cpp
    core/src/yrpp/PlanningTokenClassState.cpp
    core/src/yrpp/PlanningTokenClassLifecycle.cpp
    core/src/yrpp/PlanningBranchClass.cpp
    core/src/yrpp/PlanningNodeClassQueries.cpp
    core/src/yrpp/PlanningNodeClassLifecycle.cpp
    core/src/yrpp/TechnoClassCloak.cpp
    core/src/yrpp/HouseClassThreat.cpp
    core/src/yrpp/FootClassArrival.cpp
    core/src/yrpp/FootClassUpdate.cpp
    core/src/yrpp/MapClassContent.cpp
    core/src/yrpp/CellClassAttributes.cpp
    core/src/yrpp/MissionClassLifecycle.cpp
    core/src/yrpp/MissionClassOrders.cpp
    core/src/yrpp/RadioClassLifecycle.cpp
    core/src/yrpp/TechnoClassLifecycle.cpp
    core/src/yrpp/FootClassLifecycle.cpp
    core/src/yrpp/FootClassActionLines.cpp
    core/src/yrpp/TechnoClassActionLines.cpp
    core/src/yrpp/FootClassDrawingDepth.cpp
    core/src/yrpp/ParasiteClass.cpp
    core/src/yrpp/LineTrail.cpp
    core/src/yrpp/FootClassDamage.cpp
    core/src/yrpp/TechnoClassDamage.cpp
    core/src/yrpp/TechnoClassTargetEvaluation.cpp
    core/src/yrpp/TechnoClassTargetScan.cpp
    core/src/yrpp/LocomotionClass.cpp
    core/src/yrpp/WalkLocomotionClass.cpp
    core/src/yrpp/WalkLocomotionClassMovement.cpp
    core/src/yrpp/InfantryClassLifecycle.cpp
    core/src/yrpp/InfantryClassDamage.cpp
    core/src/yrpp/InfantryClassDrawing.cpp
    core/src/yrpp/InfantryClassOccupation.cpp
    core/src/yrpp/InfantryClassMovement.cpp
    core/src/yrpp/InfantryClassUpdate.cpp
    core/src/yrpp/InfantryClassArrival.cpp
    core/src/yrpp/TacticalClassVisibility.cpp
    core/src/yrpp/CellSpread.cpp
    core/src/yrpp/AircraftClassArray.cpp
    core/src/yrpp/AircraftTrackerClass.cpp
    core/src/yrpp/InfantryClassPassability.cpp
    core/src/yrpp/InfantryClassAnimation.cpp
    core/src/yrpp/InfantryClassTargeting.cpp
    core/src/yrpp/InfantryClassExpiration.cpp
    core/src/yrpp/FootClassExpiration.cpp
    core/src/yrpp/FootClassPassability.cpp
    core/src/yrpp/AStarClassCosts.cpp
    core/src/yrpp/AStarClass.cpp
    core/src/yrpp/AStarClassPath.cpp
    core/src/yrpp/MapClassPathfinding.cpp
    core/src/yrpp/MapClassZones.cpp
    core/src/yrpp/UnsortedAdjacency.cpp
    core/src/yrpp/UnsortedSelection.cpp
    core/src/yrpp/DisplayClassCursor.cpp
    core/src/yrpp/GameAttackMove.cpp
    core/src/yrpp/TechnoClassPlanning.cpp
    core/src/yrpp/GamePlanning.cpp
    core/src/yrpp/GamePlanningInput.cpp
    core/src/yrpp/GamePlanningCommands.cpp
    core/src/yrpp/GamePlanningGraph.cpp
    core/src/yrpp/GamePlanningTokens.cpp
    core/src/yrpp/GameSelection.cpp
    core/src/yrpp/MapClassSelection.cpp
    core/src/yrpp/DisplayClassCommands.cpp
    core/src/yrpp/DisplayClassLeftRelease.cpp
    core/src/yrpp/VoxClass.cpp
    core/src/yrpp/VoxClassQueue.cpp
    core/src/yrpp/MapClassClip.cpp
    core/src/yrpp/HouseClassWaypoints.cpp
    core/src/yrpp/FootClassWaypoints.cpp
    core/src/yrpp/WaypointPathClass.cpp
    core/src/yrpp/Notifications.cpp
    core/src/yrpp/GameWorldState.cpp
    core/src/yrpp/CellClassPassability.cpp
    core/src/yrpp/CellClassPlacement.cpp
    core/src/yrpp/FootClassPathfinding.cpp
    core/src/yrpp/FootClassMovement.cpp
    core/src/yrpp/FootClassAttack.cpp
    core/src/yrpp/TubeClass.cpp
    core/src/yrpp/TeamClassMapExit.cpp
    core/src/yrpp/AircraftTypeClassINI.cpp
    core/src/yrpp/AircraftClassLifecycle.cpp
    core/src/yrpp/AircraftClassDamage.cpp
    core/src/yrpp/AircraftClassMovement.cpp
    core/src/yrpp/MapClassEdge.cpp
    core/src/yrpp/ObjectClassParadrop.cpp
    core/src/yrpp/AircraftClassParadrop.cpp
    core/src/yrpp/TechnoTypeClassFlight.cpp
    core/src/yrpp/FlyLocomotionClass.cpp
    core/src/yrpp/TeamClass.cpp
    core/src/yrpp/ScriptClass.cpp
    core/src/yrpp/TechnoClassExpiration.cpp
    core/src/yrpp/AbstractClassExpiration.cpp
    core/src/yrpp/BuildingClassExpiration.cpp
    core/src/yrpp/TechnoClassTargeting.cpp
    core/src/yrpp/TechnoClassRange.cpp
    core/src/yrpp/UnsortedVisualGlobals.cpp
    core/src/yrpp/UnsortedCOMGlobals.cpp
    core/src/yrpp/BulletClassLifecycle.cpp
    core/src/yrpp/BulletClassPlacement.cpp
    core/src/yrpp/BulletClassExplosion.cpp
    core/src/yrpp/BulletClassUpdate.cpp
    core/src/yrpp/BulletClassDrawing.cpp
    core/src/yrpp/ObjectClassPlacement.cpp
    core/src/yrpp/ObjectClassDamage.cpp
    core/src/yrpp/MapClassTrajectory.cpp
    core/src/yrpp/TechnoClassFireControl.cpp
    core/src/yrpp/TechnoClassFireCoordinates.cpp
    core/src/yrpp/TechnoClassDrawingDepth.cpp
    core/src/yrpp/TechnoClassFire.cpp
    core/src/yrpp/TechnoClassGattling.cpp
    core/src/yrpp/MapClassDamage.cpp
    core/src/yrpp/HouseClassArmor.cpp
    core/src/yrpp/HouseClassOwnership.cpp
    core/src/yrpp/Matrix3DRotation.cpp
    core/src/yrpp/Matrix3DRamp.cpp
    core/src/yrpp/Matrix3DTransforms.cpp
    core/src/yrpp/Quaternion.cpp
    core/src/yrpp/TrajectoryHelper.cpp
    core/src/yrpp/PassengersClassExpiration.cpp
    core/src/yrpp/CaptureManagerClassExpiration.cpp
    core/src/yrpp/CaptureManagerClassDrawing.cpp
    core/src/yrpp/CaptureManagerClass.cpp
    core/src/yrpp/TemporalClassExpiration.cpp
    core/src/yrpp/CellClassContent.cpp
    core/src/yrpp/CellClassExpiration.cpp
    core/src/yrpp/MapClassExpiration.cpp
    core/src/yrpp/LogicClassExpiration.cpp
    core/src/yrpp/ObjectClassExpiration.cpp
    core/src/yrpp/RadioClassExpiration.cpp
    core/src/yrpp/MapClassFloorHeight.cpp
    core/src/yrpp/InfantryTypeClassINI.cpp
    core/src/yrpp/TechnoClassExtras.cpp
    core/src/yrpp/TechnoClassDrawingBehind.cpp
    core/src/yrpp/BuildingClassDrawingInfo.cpp
    core/src/yrpp/TechnoClassHealthBar.cpp
    core/src/yrpp/HouseClassMapLifecycle.cpp
    core/src/yrpp/TerrainClassLifecycle.cpp
    core/src/yrpp/AnimClassLifecycle.cpp
    core/src/yrpp/AnimClassFlaming.cpp
    core/src/yrpp/BounceClass.cpp
    core/src/yrpp/CellClassWalls.cpp
    core/src/yrpp/AnimClassExtras.cpp
    core/src/yrpp/GameOptionsClass.cpp
    core/src/yrpp/LogicClass.cpp
    core/src/yrpp/LogicClassMembership.cpp
    core/src/yrpp/LayerClass.cpp
    core/src/yrpp/LayerClassStream.cpp
    core/src/yrpp/HouseClassPower.cpp
    core/src/yrpp/HouseClassProduction.cpp
    core/src/yrpp/HouseClassProductionCommands.cpp
    core/src/yrpp/HouseClassSuperWeapons.cpp
    core/src/yrpp/FactoryClassPower.cpp
    core/src/yrpp/FactoryClassProduction.cpp
    core/src/yrpp/UnitClassProduction.cpp
    core/src/yrpp/UnitClassHarvest.cpp
    core/src/yrpp/FootClassHarvest.cpp
    core/src/yrpp/BuildingClassRefinery.cpp
    core/src/yrpp/AbstractClassStorage.cpp
    core/src/yrpp/TeleportLocomotionClass.cpp
    core/src/yrpp/BuildingClassProduction.cpp
    core/src/yrpp/SidebarClassProduction.cpp
    core/src/yrpp/HouseClassBuildEligibility.cpp
    core/src/yrpp/HouseClassCredits.cpp
    core/src/yrpp/ObjectTypeClassProduction.cpp
    core/src/yrpp/TechnoTypeClassProduction.cpp
    core/src/yrpp/TechnoTypeClassPlacement.cpp
    core/src/yrpp/SuperClassPower.cpp
    core/src/yrpp/TechnoClassProduction.cpp
    core/src/yrpp/BuildingClassPower.cpp
    core/src/yrpp/TiberiumClassLogic.cpp
    core/src/yrpp/PriorityQueueClass.cpp
    core/src/yrpp/GameMainLoop.cpp
    core/src/game_loop.cpp
    core/src/yrpp/BuildingClassDestruction.cpp
    core/src/yrpp/BuildingClassLifecycle.cpp
    core/src/yrpp/BuildingClassOccupation.cpp
    core/src/yrpp/BuildingClassOwnership.cpp
    core/src/yrpp/BuildingClassCombat.cpp
    core/src/yrpp/BuildingClassFireCoordinates.cpp
    core/src/yrpp/BuildingClassInput.cpp
    core/src/yrpp/BuildingClassCoordinates.cpp
    core/src/yrpp/BuildingTypeClassCoordinates.cpp

    core/src/yrpp/TechnoClassRadar.cpp
    core/src/yrpp/BuildingClassRadar.cpp
    core/src/yrpp/RadarClassTracking.cpp
    core/src/yrpp/MapClassVisibility.cpp
    core/src/yrpp/RadarClassRefresh.cpp
    core/src/yrpp/RadarEventClassDrawing.cpp
    core/src/yrpp/SurfaceGradient.cpp
    core/src/yrpp/RadarEventClass.cpp
    core/src/yrpp/PowerClassDrawing.cpp
    core/src/yrpp/TabClassInput.cpp
    core/src/yrpp/BitFontDrawing.cpp
    core/src/yrpp/RadarClassState.cpp
    core/src/yrpp/SidebarClassInput.cpp
    core/src/yrpp/ShapeButtonClass.cpp
    core/src/yrpp/ToggleClass.cpp
    core/src/yrpp/ControlClass.cpp
    core/src/yrpp/ScrollClassInput.cpp
    core/src/yrpp/MouseClassInput.cpp
    core/src/yrpp/RadarClassInput.cpp
    core/src/yrpp/RadarClassAction.cpp
    core/src/yrpp/RadarClassNavigation.cpp
    core/src/yrpp/RadarClassButtons.cpp
    core/src/yrpp/GScreenClassInput.cpp
    core/src/yrpp/InputManagerClass.cpp
    core/src/yrpp/GadgetClass.cpp
    core/src/yrpp/LinkClass.cpp
    ${ra2_palette_sources}
    core/src/yrpp/TaskForceClassStream.cpp
    core/src/yrpp/SideClassStream.cpp
    core/src/yrpp/ScriptTypeClassStream.cpp
    core/src/yrpp/AbstractTypeClassStream.cpp
    core/src/type_stream.cpp
    core/src/yrpp/TaskForceClassINI.cpp
    core/src/yrpp/TerrainTypeClassINI.cpp
    core/src/yrpp/OverlayTypeClassINI.cpp
    core/src/yrpp/SmudgeTypeClassINI.cpp
    core/src/yrpp/ObjectTypeClassINI.cpp
    core/src/type_resources.cpp
    core/src/yrpp/FileSystem.cpp
    core/src/yrpp/FileSystemTheaterPalette.cpp
    core/src/yrpp/TagClassLifecycle.cpp
    core/src/yrpp/TEventClassRuntime.cpp
    core/src/yrpp/TriggerClassRuntime.cpp
    core/src/yrpp/TagClassRuntime.cpp
    core/src/yrpp/TagTypeClassRuntime.cpp
    core/src/yrpp/TActionClassRuntime.cpp
    core/src/yrpp/TriggerClassLifecycle.cpp
    core/src/yrpp/TEventClassLifecycle.cpp
    core/src/yrpp/TActionClassLifecycle.cpp
    core/src/yrpp/BulletTypeClassLifecycle.cpp
    core/src/yrpp/BulletTypeClassINI.cpp
    core/src/yrpp/BulletTypeClassCRC.cpp
    core/src/yrpp/ParticleTypeClassLifecycle.cpp
    core/src/yrpp/ParticleTypeClassINI.cpp
    core/src/yrpp/ParticleSystemTypeClassINI.cpp
    core/src/yrpp/ParticleClassLifecycle.cpp
    core/src/yrpp/ParticleClassSpark.cpp
    core/src/yrpp/ParticleClassSmoke.cpp
    core/src/yrpp/ParticleSystemClassSmoke.cpp
    core/src/yrpp/ParticleClassDrawing.cpp
    core/src/yrpp/ParticleSystemClassLifecycle.cpp
    core/src/yrpp/ParticleSystemClassSpark.cpp
    core/src/yrpp/ParticleSystemClassDrawing.cpp
    core/src/yrpp/WarheadTypeClassLifecycle.cpp
    core/src/yrpp/WarheadTypeClassINI.cpp
    core/src/yrpp/WarheadTypeClassCRC.cpp
    core/src/yrpp/VoxelAnimTypeClassLifecycle.cpp
    core/src/yrpp/TiberiumClassLifecycle.cpp
    core/src/yrpp/CampaignClassLifecycle.cpp
    core/src/yrpp/AITriggerTypeClassLifecycle.cpp
    core/src/yrpp/UnitTypeClassLifecycle.cpp
    core/src/yrpp/TagTypeClassLifecycle.cpp
    core/src/yrpp/InfantryTypeClassLifecycle.cpp
    core/src/yrpp/SuperWeaponTypeClassLifecycle.cpp
    core/src/yrpp/TriggerTypeClassLifecycle.cpp
    core/src/yrpp/WeaponTypeClassLifecycle.cpp
    core/src/yrpp/WeaponTypeClassINI.cpp
    core/src/yrpp/WeaponTypeClassParameters.cpp
    core/src/yrpp/WeaponTypeClassCRC.cpp
    core/src/yrpp/WeaponTypeClassStream.cpp
    core/src/yrpp/AnimTypeClassLifecycle.cpp
    core/src/yrpp/BuildingTypeClassLifecycle.cpp
    core/src/yrpp/TeamTypeClassLifecycle.cpp
    core/src/yrpp/TechnoTypeClassLifecycle.cpp
    core/src/yrpp/AircraftTypeClassLifecycle.cpp
    core/src/yrpp/HouseTypeClassLifecycle.cpp
    core/src/yrpp/ParticleSystemTypeClassLifecycle.cpp
    core/src/version.cpp
    core/src/type_drawing.cpp
    core/src/yrpp/IsometricTileTypeClassDrawing.cpp
    core/src/yrpp/SmudgeTypeClassDrawing.cpp
    core/src/yrpp/OverlayTypeClassDrawing.cpp
    core/src/yrpp/CampaignClassTrivial.cpp
    core/src/yrpp/ParticleSystemTypeClassTrivial.cpp
    core/src/yrpp/ParticleTypeClassTrivial.cpp
    core/src/yrpp/BulletTypeClassTrivial.cpp
    core/src/yrpp/VoxelAnimTypeClassTrivial.cpp
    core/src/yrpp/AnimTypeClassTrivial.cpp
    core/src/yrpp/AircraftTypeClassTrivial.cpp
    core/src/yrpp/TechnoTypeClassTrivial.cpp
    core/src/yrpp/ObjectTypeClassTrivial.cpp
    core/src/yrpp/TaskForceClass.cpp
    core/src/yrpp/SideClass.cpp
    core/src/yrpp/ScriptTypeClass.cpp
    core/src/yrpp/InfantryTypeClassIdentity.cpp
    core/src/yrpp/UnitTypeClassIdentity.cpp
    core/src/yrpp/AircraftTypeClassIdentity.cpp
    core/src/yrpp/BuildingTypeClassCosts.cpp
    core/src/yrpp/BuildingTypeClassIdentity.cpp
    core/src/yrpp/WeaponTypeClassIdentity.cpp
    core/src/yrpp/WarheadTypeClassIdentity.cpp
    core/src/yrpp/SuperWeaponTypeClassIdentity.cpp
    core/src/yrpp/AnimTypeClassIdentity.cpp
    core/src/yrpp/VoxelAnimTypeClassIdentity.cpp
    core/src/yrpp/BulletTypeClassIdentity.cpp
    core/src/yrpp/ParticleTypeClassIdentity.cpp
    core/src/yrpp/ParticleSystemTypeClassIdentity.cpp
    core/src/yrpp/HouseTypeClassIdentity.cpp
    core/src/yrpp/SideClassIdentity.cpp
    core/src/yrpp/CampaignClassIdentity.cpp
    core/src/yrpp/ScriptTypeClassIdentity.cpp
    core/src/yrpp/TaskForceClassIdentity.cpp
    core/src/yrpp/TeamTypeClassIdentity.cpp
    core/src/yrpp/AITriggerTypeClassIdentity.cpp
    core/src/yrpp/TriggerTypeClassIdentity.cpp
    core/src/yrpp/TagTypeClassIdentity.cpp
    core/src/yrpp/TiberiumClassIdentity.cpp
    ${ra2_clock_sources}
    core/src/yrpp/Fundamentals.cpp
    core/src/yrpp/RandomizerGlobals.cpp
    core/src/yrpp/ScenarioClassGlobals.cpp
    core/src/yrpp/SuperClassLightingGlobals.cpp
    core/src/scenario_runtime_host.cpp
    core/src/map_runtime_host.cpp
    core/src/map_globals_host.cpp
    core/src/game_ui_globals_host.cpp
    core/src/ui_resources.cpp
    core/src/game_ui_runtime.cpp
    core/src/tooltip_platform.cpp
    core/src/yrpp/ToolTipManager.cpp
    core/src/yrpp/CCToolTip.cpp
    core/src/yrpp/BitText.cpp
    core/src/yrpp/DisplayClassToolTip.cpp
    core/src/yrpp/CellClassToolTip.cpp
    core/src/yrpp/BuildingClassToolTip.cpp
    core/src/yrpp/AircraftClassToolTip.cpp
    core/src/yrpp/InfantryClassToolTip.cpp
    core/src/yrpp/UnitClassToolTip.cpp
    core/src/yrpp/GScreenClassDrawing.cpp
    core/src/yrpp/DisplayClassDrawing.cpp
    core/src/yrpp/RadarClassDrawing.cpp
    core/src/yrpp/RadarClassNames.cpp
    core/src/yrpp/SidebarClassDrawing.cpp
    core/src/yrpp/TabClassDrawing.cpp
    core/src/map_view.cpp
    core/src/yrpp/TacticalClassHost.cpp
    core/src/yrpp/IsometricTileTypeClassTheater.cpp
    core/src/yrpp/IsometricTileTypeClassTheaterGlobals.cpp
    core/src/yrpp/TheaterResources.cpp
    core/src/yrpp/MixFileClassTerrainResources.cpp
    core/src/yrpp/MixFileClassSidebarResources.cpp
    ${ra2_map_root_sources}
    ${ra2_scenario_sources}
    ${ra2_rules_sources}
    core/src/rules_runtime_host.cpp
    core/src/yrpp/MissionControlClassGlobals.cpp
    core/src/yrpp/RulesClassGlobals.cpp
    core/src/yrpp/GroundTypeGlobals.cpp
    core/src/yrpp/PowerupsGlobals.cpp
    core/src/yrpp/AnimTypeClassGlobals.cpp
    core/src/yrpp/MovieInfoGlobals.cpp

    # Shared core memory implementation, filename ownership and YRpp foundation.
    ${ra2_filesystem_name_sources}
    ${ra2_core_memory_sources}
    ${ra2_audio_sources}
    core/src/audio_backend_host.cpp
    ${ra2_video_sources}
    core/src/video_backend_host.cpp
    core/src/yrpp/StringTable.cpp
    core/src/yrpp/LCWPipe.cpp
    core/src/yrpp/LCWStraw.cpp
    core/src/yrpp/LZOPipe.cpp
    core/src/yrpp/LZOStraw.cpp
    core/src/yrpp/CRC.cpp
    core/src/yrpp/Straws.cpp
    core/src/yrpp/Pipes.cpp
    core/src/yrpp/ArrayClasses.cpp
    core/src/yrpp/BasicStructures.cpp
    core/src/yrpp/GenericList.cpp
    # Minimal production software Surface and original drawing-buffer state.
    core/src/yrpp/Surface.cpp
    core/src/yrpp/BitFont.cpp
    core/src/yrpp/DrawingBuffers.cpp
    core/src/yrpp/DrawingColorState.cpp

    # File chain, INI and MIX resources with standalone storage.
    ${ra2_file_chain_sources}
    ${ra2_ini_sources}
    core/src/yrpp/CCINIClassGlobals.cpp
    core/src/ini_runtime_host.cpp
    core/src/filesystem/resource_environment.cpp
    core/src/filesystem/search_paths.cpp
    core/src/yrpp/PKey.cpp
    core/src/yrpp/MixFileClass.cpp
    core/src/filesystem/resource_context.cpp
    core/src/filesystem/resource_globals.cpp
    core/src/filesystem/resource_globals_host.cpp
    core/src/filesystem/mix_crypto.cpp
    third_party/xcc/blowfish.cpp

    # Resource startup and public host API.
    core/src/yrpp/MixFileClassBootstrap.cpp
    core/src/filesystem/bootstrap_services.cpp
    core/src/filesystem/resource_startup.cpp
    core/src/filesystem/resource_api.cpp

    # Map resource metadata; game/renderer startup remains outside this module.
    core/src/yrpp/Theater.cpp
    core/src/yrpp/TheaterGlobals.cpp
    core/src/yrpp/AbstractClass.cpp
    core/src/yrpp/AbstractClassStream.cpp
    core/src/yrpp/SwizzleManagerClass.cpp
    core/src/yrpp/AbstractClassGeometry.cpp
    core/src/yrpp/ColorSchemePalette.cpp
    core/src/yrpp/ColorScheme.cpp
    core/src/yrpp/YRMathTrigonometry.cpp
    core/src/yrpp/YRMath.cpp
    core/src/yrpp/AbstractClassDeletion.cpp
    core/src/yrpp/AbstractClassTargeting.cpp
    core/src/abstract_globals_host.cpp
    core/src/target_registry.cpp
    core/src/yrpp/TargetClass.cpp
    core/src/yrpp/AbstractTypeClass.cpp
    core/src/yrpp/ObjectTypeClass.cpp
    core/src/yrpp/IsometricTileTypeClass.cpp
    core/src/yrpp/IsometricTileTypeClassTMP.cpp
    core/src/yrpp/IsometricTileClass.cpp
    core/src/yrpp/OverlayTypeClass.cpp
    core/src/yrpp/OverlayClass.cpp
    core/src/yrpp/TerrainTypeClass.cpp
    core/src/yrpp/TerrainClass.cpp
    core/src/yrpp/SmudgeTypeClassPlacement.cpp
    core/src/yrpp/SmudgeTypeClass.cpp
    core/src/yrpp/SmudgeClass.cpp
    core/src/yrpp/SmudgeClassINI.cpp
    core/src/yrpp/HouseClassINI.cpp
    core/src/yrpp/OverlayClassINI.cpp
    core/src/yrpp/TerrainClassINI.cpp
    core/src/yrpp/BuildingClassINI.cpp
    core/src/yrpp/InfantryClassINI.cpp
    core/src/yrpp/UnitClassINI.cpp
    core/src/scenario_objects.cpp
    core/src/yrpp/TeamTypeClassINI.cpp
    core/src/yrpp/TagTypeClassINI.cpp
    core/src/yrpp/TriggerTypeClassINI.cpp
    core/src/scenario_type_loading.cpp
    core/src/scenario_campaign.cpp
    core/src/scenario_reinforcements.cpp
    core/src/yrpp/AITriggerTypeClassINI.cpp
    core/src/yrpp/TeamTypeClassTaskForce.cpp
    core/src/yrpp/BuildingClassPlacement.cpp
    core/src/yrpp/TerrainClassPlacement.cpp
    core/src/yrpp/CellClass.cpp
    core/src/yrpp/CellClassLifecycle.cpp
    core/src/yrpp/MapClass.cpp
    core/src/yrpp/MapClassIsoMapPack.cpp
    core/src/yrpp/DisplayClassLoading.cpp
    core/src/yrpp/MixFileClassMapResources.cpp
    core/src/yrpp/BuildingLightClass.cpp
    core/src/yrpp/SpotlightClass.cpp
    core/src/yrpp/LightSourceClass.cpp
    core/src/yrpp/CellClassLightSource.cpp
    core/src/yrpp/CellClassTerrain.cpp
    core/src/yrpp/CellClassVariants.cpp
    core/src/yrpp/CellClassDrawing.cpp
    core/src/yrpp/CellClassRadar.cpp
    core/src/yrpp/RadarClassTerrain.cpp
    core/src/yrpp/RadarClassRebuild.cpp
    core/src/yrpp/MapClassVisibleRect.cpp
    core/src/yrpp/RadarClassVisibility.cpp
    core/src/yrpp/CellClassShroud.cpp
    core/src/yrpp/DisplayClassVisibility.cpp
    core/src/yrpp/MapClassRevealCheck.cpp
    core/src/yrpp/MapClassSight.cpp
    core/src/yrpp/TechnoClassSight.cpp
    core/src/yrpp/AircraftClassSight.cpp
    core/src/yrpp/FPSCounter.cpp
    core/src/yrpp/TacticalClassDrawing.cpp
    core/src/yrpp/TacticalClassRender.cpp
    core/src/yrpp/TacticalClassBackground.cpp
    core/src/yrpp/TacticalClassObjects.cpp
    core/src/yrpp/IsometricTileTypeClassShadow.cpp
    core/src/yrpp/AlphaShapeClassDrawing.cpp
    core/src/yrpp/AlphaShapeClass.cpp
    core/src/yrpp/CellClassBackground.cpp
    core/src/yrpp/DrawingRectangle.cpp
    core/src/yrpp/ObjectClassDrawing.cpp
    core/src/yrpp/BuildingClassVisibility.cpp
    core/src/yrpp/UnitClassVisibility.cpp
    core/src/yrpp/TacticalClassDrawingExtras.cpp
    core/src/yrpp/TacticalClassPicking.cpp
    core/src/yrpp/TacticalClassSelection.cpp
    core/src/yrpp/DisplayClassSelection.cpp
    core/src/yrpp/BuildingClassSelection.cpp
    core/src/yrpp/IsometricTileTypeClassMapImages.cpp

    # Standalone SHP decoding; the other image classes are not included.
    core/src/images/shp_decode.cpp
    core/src/yrpp/SHPStruct.cpp)
target_sources(ra2_core PRIVATE ${ra2_voxel_format_sources})
add_library(ra2::core ALIAS ra2_core)
ra2_configure_cpp_target(ra2_core)
target_compile_definitions(ra2_core PRIVATE RA2_PROJECT_VERSION="${PROJECT_VERSION}")
# Keep numerical policy private to the standalone implementation.
if(MSVC)
    target_compile_options(ra2_core PRIVATE /fp:strict)
else()
    target_compile_options(ra2_core PRIVATE -fno-fast-math -ffp-contract=off)
endif()
target_include_directories(ra2_core PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/core/include")
ra2_core_private_includes(ra2_core)
set_target_properties(ra2_core PROPERTIES POSITION_INDEPENDENT_CODE ON)
if(WIN32)
    target_link_libraries(ra2_core PRIVATE winmm)
endif()
